### ISSUE TITLE
Handling loader output

### ISSUE THREAD

**Issue by rezenvar** [acss-io/webpack-atomizer-loader#13]
Is there way to handle loader output file? For example minify it with css-loader.
In my project i use atomizer-loader for vue files.

Rule for vue files:
```
 {
                test: /\.vue$/,
                use: [
                    'vue-loader',
                    {
                        loader: 'webpack-atomizer-loader',
                        options: {
                            configPath: root('atomicCssConfig.js')
                        }
                    }

                ],
                exclude: /node_modules/,
          },
```
it correctly outputs generated css file, but i want to minify it.

**Comment by tom76kimo** [comment]
I haven't test it, but can you try to add your `css-loader` after `webpack-atomizer-loader`?

**Comment by rezenvar** [comment]
Actually, loader always returns source passed into it. And always write result css file to dist folder(from config).
There is no option now to pass result css to other loader. 
I tried to implement this feature but I have no experience in writing loaders for webpack.

**Comment by tom76kimo** [comment]
Add support of output minimized css file in this PR

https://github.com/acss-io/webpack-atomizer-loader/pull/14

**Comment by tom76kimo** [comment]
The change has applied to version [`0.4.0`](https://github.com/acss-io/webpack-atomizer-loader/releases/tag/0.4.0)
