### ISSUE TITLE
Does anyone know how to use it with Vue.js?

### ISSUE THREAD

**Issue by jitendravyas** [acss-io/webpack-atomizer-loader#15]

**Comment by alexgarrett** [comment]
I've been successfully using this with Vue the following way. Add this to your `modules.rules` array.

```
{
    test: /\.vue?$/,
    exclude: /(node_modules)/,
    loader: 'webpack-atomizer-loader',
    query: {
        configPath: path.resolve('./acss.js')
    }
}
```

Here's a basic config (`acss.js` in the root directory of the project):

```
module.exports = {
    cssDest: './assets/styles/acss/app.css',
    options: {
        //
    },
    configs: {
        breakPoints: {
            sm: '@media screen(min-width=750px)',
            md: '@media(min-width=1000px)',//
            lg: '@media(min-width=1200px)'
        },
        custom: {
            //
        },
        classNames: []
    }
}
```

I then include the generated `acss/app.css` into my `app.scss` stylesheet. I'm specifically using this with Nuxt.js, but shouldn't be too much different with Vue CLI.

**Comment by jobsFu** [comment]
if vue cli3 ，       
 how to do that ？

**Comment by AntonioRedondo** [comment]
Perhaps a bit late response. But I just created a [pull request](https://github.com/acss-io/webpack-atomizer-loader/pull/27) to improve the documentation and explaining using the loader with Vue.js a bit better. `README.md` now looks like [this](https://github.com/acss-io/webpack-atomizer-loader/blob/cc4ef150cead0e8804e69676eb39fcefb8834142/README.md#usage-with-react-or-vue).

**Comment by dword-design** [comment]
In case you use Nuxt, you can use [nuxt-atomizer](https://github.com/dword-design/nuxt-atomizer). Install it via `npm install nuxt-atomizer` and add it to `nuxt.config.js`:

```js
export default {
  modules: [
    'nuxt-atomizer',
  ],
}
```
