### ISSUE TITLE
Issues using .vue files

### ISSUE THREAD

**Issue by chinchang** [acss-io/webpack-atomizer-loader#17]
I have a simple configuration where I add this loader to `.vue` (Vue.js Single file component) files. According to my atomizer config, this loader generates `main.css` file. But I now face 3 issues:

1. Is `require('./main.css')` the correct way of loading that generated CSS file as a dependency? What if I don't commit this generated file in version control? Webpack would give error then.
2. Even with the above mentioned `require('./main.css')` method, change in `.vue` files, trigger `main.css` generation. But, change in `main.css` again triggers the webpack's watch. So single change is causing watch compilation to trigger 2-4 times.
3. The generated `main.css` always contains the previous classes and keep appending new ones to it. Probably related to point no. 2 above.

If we could have an example of using this plugin correctly with webpack, that would really help.

**Update:**
Point no. 3 seems to be happening because of [bug in the loader code](https://github.com/acss-io/webpack-atomizer-loader/blob/master/lib/atomicLoader.js#L86). The loader keeps using the same acss config without cloning into a new object. And as far as atomizer goes, it mutates the config object passed to it. Cloning the config before passing to `getConfig` function seems to fix the issue.

**Comment by tom76kimo** [comment]
Great point! Will look into it.

**Comment by dsaket** [comment]
Any update on this issue??

**Comment by redonkulus** [comment]
@chinchang we fixed the mutating config issue in atomizer recently, so this should resolve your issue in #3 https://github.com/acss-io/atomizer/pull/392

Want to give it another try? (if any of this is still relevant)
