### ISSUE TITLE
a way to use while retaining hot reload?

### ISSUE THREAD

**Issue by VinSpee** [acss-io/webpack-atomizer-loader#18]
often in webpack projects, the setup will be as follows:

`index.js`:

```jsx
import 'style.css';
…
```
and there will be a series of css loaders set up to handle the import and move it somewhere.

with `webpack-atomizer-loader`, that creates a problem, as the atomizer just writes the changes to a css file, which is typically imported by a `/\.jsx?/` file. That means that the jsx file detects a change, atomizer runs, generates the css file, the jsx imports the css file, etc… and so the loop begins.

The only workaround is to import the css file using something like `html-webpack-include-assets-plugin`. This means you no longer get hot reloading, a total productivity killer.

How can we smartly address this issue or what other ways could we handle the creation of CSS output?

was brought up here: https://gitter.im/acss-io/atomizer?at=5a491c980163b028109945ba

**Comment by tom76kimo** [comment]
To break the loop, you should make CSS file change won't trigger the js/jsx file detection. To achieve that, you can use `oneOf` in your webpack config. Here is an example by `create-react-app`. https://github.com/facebookincubator/create-react-app/blob/a1c5b8f7054ac0ac708a498c2a6308f3ed1cb8f0/packages/react-scripts/config/webpack.config.dev.js#L151-L232

After that, the flow will be js/jsx file change -> atomizer runs -> css file change -> `css-loader`, `style-loader` runs -> end.

**Comment by VinSpee** [comment]
Thank you! I’ll try this tomorrow and update the issue with the configure that worked.

**Comment by VinSpee** [comment]
@tom76kimo was indeed correct – the secret lies in webpack's `oneOf`:

```js
    "oneOf": [{
        "loader": [{
            "loader": "style-loader"
        }, {
            "loader": "css-loader",
            "options": {
                "modules": true,
                "localIdentName": "[local]__[hash:base64:5]",
                "importLoaders": 1,
                "sourceMap": false
            }
        }, {
            "loader": "postcss-loader",
            "options": {
                "ident": "postcss",
                "sourceMap": true,
                "plugins": [null]
            }
        }]
    }, {
        "loader": "webpack-atomizer-loader",
        "options": {
            "configPath": …,
            "minimize": false
        }
    }]
```

worked for me!

**Comment by tom76kimo** [comment]
Great!

**Comment by chinchang** [comment]
@VinSpee In your working code, I suppose you have missed the rule's test keys intentionally, correct? The first rule must be for `.css` and the second for `.jsx`?

**Comment by VinSpee** [comment]
correct, I didnt want to assume any extensions

**Comment by chinchang** [comment]
Hmm. Strange then...same setup doesn't work for me with Vue. Instead of `.jsx` I have `.vue` as test condition.

**Comment by VinSpee** [comment]
```js
{
    oneOf: [{
        test: /\.(css|less|s[ac]ss|styl)$/,
        include: ["./src/components", "./src/routes"],
        loader: [{
            loader: "extract-text-webpack-plugin/dist/loader.js",
            options: {
                omit: 1,
                remove: true
            }
        }, {
            loader: "style-loader"
        }, {
            loader: "css-loader",
            options: {
                modules: true,
                localIdentName: "[local]__[hash:base64:5]",
                importLoaders: 1,
                sourceMap: false
            }
        }, {
            loader: "postcss-loader",
            options: {
                ident: "postcss",
                sourceMap: true,
            }
        }]
    }, {
        test: /\.(j|t)sx?$/,
        loader: "webpack-atomizer-loader",
        options: {
            configPath: "./atomicCSSConfig.js",
            minimize: false
        }
    }]
}
```

that is the full modification @chinchang

**Comment by chinchang** [comment]
Thanks for that code @VinSpee. Seems my issue is actually because of `vue-loader` (used for parsing single file vue components) which internally runs `css-loader` and `style-loader`. It still runs no matter what I do in my webpack config :|
