### ISSUE TITLE
Output multiple files based on entry points

### ISSUE THREAD

**Issue by redonkulus** [acss-io/webpack-atomizer-loader#24]
@tom76kimo @src-code 

I'd like to be able to output a separate atomic CSS file per entry point in my webpack config. This way I can load separate CSS files in my site, based on the route that is requested. 

For example, given the following webpack config:

<details>
  <summary>webpack.config.js</summary>

```js
module.exports = {
    mode: 'production',
    entry: {
        page1: './path/to/page1.marko',
        page2: './path/to/page2.marko'
    },
    output: {
        filename: '[name].js',
        path: 'dist/
    },
    resolve: {
        extensions: ['.js', '.marko']
    },
    module: {
        rules: [
            {
                test: /\.marko$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'webpack-atomizer-loader',
                    options: {
                        minimize: true
                    }
                }
            },
            {
                test: /\.marko$/,
                loader: 'marko-loader'
            }
        ]
    }
};
```
</details>
<hr>

Should output:

```
- /build/css/page1.css
- /build/css/page2.css
```

Thoughts?

**Comment by tom76kimo** [comment]
Dest path indicated in `atomCssConfig` file currently. If need to separate the output file, we can do like this https://github.com/acss-io/webpack-atomizer-loader/blob/master/example/webpack.config.js#L20-L21 with separated config file and different `cssDest`.

For generating separate output file based on webpack entry, I don't have an idea at this moment.

**Comment by redonkulus** [comment]
@tom76kimo thanks for the response. The cssDest helps for outputting the file, but we need a way to limit the "input" that atomizer is run against. I'd have to looking to webpack docs to figure out if this is possible in a loader; I'm not sure at the moment.

**Comment by src-code** [comment]
I don't think we want to tie the `cssDest` to the config file - after all, we will share configs across all routes (eg custom values).  What we really need is a way to map entrypoint -> cssDest

**Comment by redonkulus** [comment]
This is no longer needed.
