### ISSUE TITLE
Inline output into style tag

### ISSUE THREAD

**Issue by Tylerian** [acss-io/webpack-atomizer-loader#26]
Is there any simple way of inlining atomizer's output css into a style tag inside the <head> of the document instead of adding it to a css file?

Sites like tinder are already doing it to optimize the First Meaningful Paint.

**Comment by AntonioRedondo** [comment]
Perhaps a bit late response. But I just created a [pull request](https://github.com/acss-io/webpack-atomizer-loader/pull/27) to improve the documentation and explaining using the loader to inline the CSS generated. `README.md` now looks like [this](https://github.com/acss-io/webpack-atomizer-loader/blob/cc4ef150cead0e8804e69676eb39fcefb8834142/README.md#usage-with-mini-css-extract-plugin-and-webpack-html-plugin).

If you want to inline the CSS into the HTML with a `<style>` element you'll also have to add [`html-webpack-inline-source-plugin`](https://github.com/DustinJackson/html-webpack-inline-source-plugin):

```javascript
plugins: [
    new HtmlWebpackPlugin({
        template: 'src/originTemplate.htm',
        filename: 'dist/destinationFile.htm',
        inlineSource: ".(css)$", // html-webpack-inline-source-plugin option
    }),
    new MiniCssExtractPlugin(),
    new HtmlWebpackInlineSourcePlugin() // This plugin will inline the CSS into the HTML
]
```

**Comment by redonkulus** [comment]
Thanks for answering this @AntonioRedondo
