### ISSUE TITLE
Transfer repo to Atomic CSS Github organization

### ISSUE THREAD

**Issue by pankajparashar** [acss-io/webpack-atomizer-loader#4]
As part of this [issue](https://github.com/yahoo/acss-site/issues/106) we're planning to bring all the build tools, plugins etc related to Atomic CSS under a single umbrella.

Would you be alright to transfer this repo under the Atomic CSS organization? You would still hold complete control over the repository and will also be added to the Atomic CSS organization.

I would love to answer any questions that you may have. Thanks for all the work that you have done so far.

**Comment by tom76kimo** [comment]
After reviewing the issue and discussions, I think I agree with the idea. 👍

**Comment by pankajparashar** [comment]
Alright. As part of the first step, I've sent the invitation to join the organization.

**Comment by tom76kimo** [comment]
I have accepted.

**Comment by pankajparashar** [comment]
I'm thinking of using the following naming convention,
1. `webpack-atomizer-loader` (for the loader)
2. `webpack-atomizer-plugin` (for the plugin)

Hence, while transferring the repo, would you be alright to rename it to `webpack-atomizer-loader`? What are the possible problems that could emerge after renaming?

**Comment by tom76kimo** [comment]
Renaming is okay. However, I don't know how many users are using `atomic-loader` for now. If rename the repo and publish to `npm` may break the productions which include `atomic-loader`.

**Comment by pankajparashar** [comment]
Can we do it the following way?

1. Register this repo under a new npm package - `webpack-atomizer-loader`
2. Mark the existing npm package as **deprecated** (advising users to move onto the new one).
3. Transfer the repo to Atomic CSS Github organisation.

I understand this may turn out to be a lot of work! But let me know, where I can assist. Would be glad to help.

**Comment by tom76kimo** [comment]
Ok. Will do it!

**Comment by tom76kimo** [comment]
It's all done

**Comment by pankajparashar** [comment]
Excellent work @tom76kimo. Thanks so much!
