### ISSUE TITLE
Misleading README (configPath)

### ISSUE THREAD

**Issue by ejulen** [acss-io/webpack-atomizer-loader#8]
In the README example, `configPath` is set to `./atomicCssConfig.js`, it seems like the file would have to be placed inside `node_modules/webpack-atomizer-loader/dist` in order for that to work, and that is obviously no good. Maybe update the README saying something about using `__dirname` and/or `path.resolve`?

**Comment by tom76kimo** [comment]
I agree. Actually the example uses `__dirname` instead. https://github.com/acss-io/webpack-atomizer-loader/blob/master/example/webpack.config.js#L12

Will update README. Thanks.

**Comment by tom76kimo** [comment]
Updated
